#!/usr/bin/env python

"""
PLOT PROTEIN LIPID CONTACTS
plots that derive from data generated by codes/protein_lipid_contacts.py
"""

import numpy as np
#---block: what to plot
routine = ['plt'][-1:]

def make_map(dat):
	from matplotlib.ticker import MultipleLocator

	def average_set(curr_list):
		cutoff = 1
	        hist=[]
	        unique_list=sorted(set(curr_list))
	        for el in unique_list:
	                occ=curr_list.count(el)
	                if occ > cutoff:
	                        hist.append(el)
		return hist
	
	sequence=['w','m','d','n','p','e','r','y','m','d','m','s','g','y','q','m','d','m','q','g','r','w',\
	'm','d','a','q','g','r','f','n','n','p','f','g','q','m','w','h','g','r','q','g','h','y','p',\
	'g','y','m','s','s','h','s','m','y','g','r','n','m','y','n','p']
	fontSize = 10
	res_per_frame = []	
	seq = []
	curr_list = []
	frame_bin = []
	fr_count = 0

	tdat = np.transpose(dat)

	for frame in tdat:
		residues = np.where(frame!=0)[0]
	        for r in residues:
			curr_list.append(r)
	        if fr_count%25==0:
			print "HERE", curr_list
	                hist=average_set(curr_list)
	                for i in range(len(hist)):
	                        frame_bin.append(fr_count)
	                        seq.append(hist[i])
	                res_per_frame.append(len(hist))
	                curr_list=[]
	        fr_count+=1

        fig=plt.figure(1)
        plot=fig.add_subplot(111)
        plt.scatter(frame_bin,seq,s=30,marker='o',lw=0.0)
        plot.tick_params(axis='both', which='minor', labelsize=fontSize)
        #plot.yaxis.set_minor_locator(MultipleLocator(1))
        #plt.grid(b=True,which='major',linestyle='-')
        #plt.grid(b=True,which='minor',linestyle='--',alpha=0.3)
        plot.set_xlabel('Time (ns)',size=fontSize)
        plot.set_ylabel('Residue',size=fontSize)
        plot.set_yticks(np.arange(0,len(sequence)))
        plot.set_yticklabels(sequence,fontSize=fontSize)
        #plt.ylim(26.5,34.5)   
        #plt.xlim(185,1215)

	#fig=plt.figure(1)
	#ax=fig.add_subplot(111)
	#fig.suptitle('Protein/Membrane Contacts')
	#ax.set_xlabel('Time')

	#ax.set_ylabel('Residue Number')
	#ax.set_yticks(np.arange(len(sequence)))
	#ax.set_yticklabels(sequence,fontSize=5)

	##plt.imshow(x,cmap='Greys')
	#plt.scatter(frame_bin,seq,s=30,marker='o',lw=0.0)
	#plt.grid(lineStyle=':')
	picturesave('fig.%s'%('interface_probe_time.'+str(sn)),work.plotdir,backup=False,version=True,meta={},form='pdf')

def make_hist(x):
	global sn
	sequence=['w','m','d','n','p','e','r','y','m','d','m','s','g','y','q','m','d','m','q','g','r','w',\
	'm','d','a','q','g','r','f','n','n','p','f','g','q','m','w','h','g','r','q','g','h','y','p',\
	'g','y','m','s','s','h','s','m','y','g','r','n','m','y','n','p']

	m,n=x.shape
	hist = np.zeros(m)
	resnum = 0
	for i in x:
		hist[resnum]=sum(i)
		resnum+=1
	print hist

	fig=plt.figure(1)
	ax=fig.add_subplot(111)
	fig.suptitle('Residue/Lipid Contacts')
	ax.set_xlabel('Residue Number')
	ax.set_ylabel('Number of Occurrences')

	ax.set_xticks(np.arange(len(sequence)))
	ax.set_xticklabels(sequence,fontSize=5)

	plt.bar(np.arange(m),hist,width=1,edgecolor='k')
	plt.xlim(-1,len(sequence))
	picturesave('fig.%s'%('interface_probe_histogram.'+str(sn)),work.plotdir,backup=False,version=True,meta={},form='pdf')

#---block: load the calculation data
if 'data' not in globals(): 
	data,calcs = plotload('interface_probe',work)

#---block: heat map of curvature from the mesh
if 'plt' in routine:

	#---settings
	global sn
	sn = 'mk001'
	protein_lipid_contacts = data[sn]['data']
	resids_per_frame = np.transpose(protein_lipid_contacts['resids_per_frames'])
	make_map(resids_per_frame)
	make_hist(resids_per_frame)

