#!/usr/bin/env python

"""
PLOT PROTEIN LIPID CONTACTS
plots that derive from data generated by codes/protein_lipid_contacts.py
"""

import numpy as np
#---block: what to plot
routine = ['plt'][-1:]

def make_map(data):

	def average_set(curr_list):
	        hist=[]
	        unique_list=sorted(set(curr_list))
	        for el in unique_list:
	                occ=curr_list.count(el)
	                if occ > cutoff:
	                        hist.append(el-9230)
	return hist
	
	sequence=['w','m','d','n','p','e','r','y','m','d','m','s','g','y','q','m','d','m','q','g','r','w',\
	'm','d','a','q','g','r','f','n','n','p','f','g','q','m','w','h','g','r','q','g','h','y','p',\
	'g','y','m','s','s','h','s','m','y','g','r','n','m','y','n','p']

	res_per_frame = []	
	seq = []
	curr_list = []
	frame_bin = []
	fr_count = 0
	for frame in data:
		residues = np.where(frame!=0)
	        for r in residues:
			curr_list.append(res)
	        if fr_count%10==0:
	                hist=average_set(curr_list)
	                for i in range(len(hist)):
	                        frame_bin.append(fr_count)
	                        seq.append(hist[i])
	                res_per_frame.append(len(hist))
	                curr_list=[]
	        fr_count+=1

	fig=plt.figure(1)
	ax=fig.add_subplot(111)
	fig.suptitle('Protein/Membrane Contacts')
	ax.set_xlabel('Time')

	ax.set_ylabel('Residue Number')
	ax.set_yticks(np.arange(len(sequence)))
	ax.set_yticklabels(sequence,fontSize=5)

	plt.imshow(x,cmap='Greys')
	plt.grid(lineStyle=':')
	picturesave('fig.%s'%('protein_lipid_contacts_map'),work.plotdir,backup=False,version=True,meta={})

def make_hist(x):
	sequence=['w','m','d','n','p','e','r','y','m','d','m','s','g','y','q','m','d','m','q','g','r','w',\
	'm','d','a','q','g','r','f','n','n','p','f','g','q','m','w','h','g','r','q','g','h','y','p',\
	'g','y','m','s','s','h','s','m','y','g','r','n','m','y','n','p']

	m,n=x.shape
	hist = np.zeros(m)
	resnum = 0
	for i in x:
		hist[resnum]=sum(i)
		resnum+=1
	print hist

	fig=plt.figure(1)
	ax=fig.add_subplot(111)
	fig.suptitle('Residue/Lipid Contacts')
	ax.set_xlabel('Residue Number')
	ax.set_ylabel('Number of Occurrences')

	ax.set_xticks(np.arange(len(sequence)))
	ax.set_xticklabels(sequence,fontSize=5)

	plt.bar(np.arange(m),hist)
	plt.xlim(-1,len(sequence))
	picturesave('fig.%s'%('protein_lipid_contacts_histogram'),work.plotdir,backup=False,version=True,meta={})

#---block: load the calculation data
if 'data' not in globals(): 
	data,calcs = plotload('protein_lipid_contacts',work)

#---block: heat map of curvature from the mesh
if 'plt' in routine:

	#---settings
	sn = 'mk005'
	protein_lipid_contacts = data[sn]['data']
	resids_per_frame = np.transpose(protein_lipid_contacts['resids_per_frames'])
	make_map(resids_per_frame)
	make_hist(resids_per_frame)

